pipeline:
  name: "dummy_test"

  reader:
    type: "s3"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "licenses.csv"
      post_read_select_exprs:
        - "Hvfhs_license_num as licence_id"
        - "license as license_name"
      post_read_filter_expr: "license_name != 'Juno'"
    input:
      format: "csv"
      config:
        header: true
        infer_schema: true

  transformations:
    - klass: "etl.impl.transformers.transformers.GroupByFirstTransformer"
      props:
        grouping_key: "licence_id"
        agg_column: "license_name"
    - klass: "etl.impl.transformers.transformers.DateTransformer"


  writer:
    type: console
