spark.jars.packages:
  - 'org.apache.hadoop:hadoop-aws:3.3.4'
spark.hadoop.fs.s3a.endpoint: 'http://s3.eu-west-1.amazonaws.com'
spark.hadoop.fs.s3a.aws.credentials.provider: 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider'