pipeline:
  name: "taxi_trip_bach_agg_metrics"
  type: batch
  reader:
    type: "s3"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "data/storage/trips_data.parquet"
    input:
      format: "parquet"

  transformations:
    - klass: "transformers.taxi_metadata_transformers.TaxiMetadataAggTransformer"
      props:
        bucket: nalexx6-dlt-bucket
        licenses_metadata_path: "/data/storage/licenses.csv"
        zones_metadata_path: "/data/storage/zones.csv"

  writer:
    type: "postgres"
    config:
      host: "localhost"
      port: "5432"
      table_name: test_schema.taxi_metrics_agg
    output:
      config:
        mode: "overwrite"



