pipeline:
  name: "example_s3_to_s3"
  input:
    type: "s3"
    format: "csv"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "licenses.csv"
      post_read_select_exprs:
        - "Hvfhs_license_num as licence_id"
        - "license as license_name"
      post_read_filter_expr: "license_name != 'Juno'"
      header: true
      infer_schema: true

  transformations:
    klass: "etl.impl.transformers.transformers.TimestampTransformer"
#    - klass: [ "some other class"]
#      props: "some props"


  output:
    type: "s3"
    format: "parquet"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "licenses-processed-1"
      mode: "append"
