pipeline:
  name: "example_s3_to_s3"

  reader:
    type: "s3"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "licenses.csv"
      post_read_select_exprs:
        - "Hvfhs_license_num as licence_id"
        - "license as license_name"
      post_read_filter_expr: "license_name != 'Juno'"
    input:
      format: "csv"
      config:
        header: true
        infer_schema: true

  transformations:
    - klass: "etl.impl.transformers.transformers.TimestampTransformer"
    - klass: "etl.impl.transformers.transformers.DateTransformer"

  writer:
    type: "s3"
    config:
      bucket: "nalexx6-dlt-bucket"
      object_key: "licenses-processed-1"
    output:
      format: "parquet"
      config:
        mode: "append"
