name: Push code to S3

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  push_dags_lib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Publish to S3
      run: aws s3 cp --recursive ./etl  s3://${{ secrets.BUCKET_NAME }}/${{ secrets.DAGS_FOLDER }} --exclude "*.pyc"
